config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'profile' => 'profiles#me'
  get 'order/:id' => 'orders#show', as: 'order'
  post 'response_to_orders' => 'response_to_orders#create', as: 'response_to_orders'
  resources :profiles
  devise_for :workers
  resources :workers
  root to: 'pages#home'
  devise_for :customers

  resources :customers do
    resources :orders do
      member do
        put 'complete'
        put 'confirm'
      end
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
# frozen_string_literal: true

class Order < ApplicationRecord
  belongs_to :customer
  has_many :response_to_orders

  has_many_attached :images
  enum status: [:new, :completed, :in_progress], _prefix: :order

end

app/controllers/orders_controller.rb
# frozen_string_literal: true

class OrdersController < ApplicationController
  before_action :set_order, only: %i[show edit update destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.where(customer_id: params[:customer_id])
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    @workers = Worker.joins(:response_to_orders).where(response_to_orders: { order_id: params[:id]})
  end

  # GET /orders/new
  def new
    @customer = Customer.find(params[:customer_id])
    @order = @customer.orders.new
  end

  # GET /orders/1/edit
  def edit; end

  # POST /orders
  # POST /orders.json
  def create
    @customer = Customer.find(params[:customer_id])
    @order = @customer.orders.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to profile_url, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  def complete
    @order = Order.find(params[:id])
    @order.order_completed!
  end

  def confirm
    @order = Order.find(params[:id])
    @order.update_attribute(:worker_id, params[:worker_id])
    @order.order_in_progress!
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to profile_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_order
    @order = Order.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def order_params
    params.require(:order).permit(:title, :description, :address, :price, :customer_id, images: [])
  end
end

app/views/orders/_form.html.erb
<%= form_with model: [:customer, @order] do |form| %>
<% if order.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(order.errors.count, "error") %>
      prohibited this order from being saved:</h2>

    <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="field">
  <%= form.label :title %>
  <%= form.text_field :title %>
</div>

<div class="field">
  <%= form.label :description %>
  <%= form.text_field :description %>
</div>

<div class="field">
  <%= form.label :address %>
  <%= form.text_field :address %>
</div>

<div class="field">
  <%= form.label :price %>
  <%= form.number_field :price %>
</div>

<div class="field">
  <%= form.label :images %>
  <%= form.file_field :images, multiple: true %>
</div>

<div class="actions">
  <%= form.submit %>
</div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', profile_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orders</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Address</th>
      <th>Price</th>
      <th>Customer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.title %></td>
        <td><%= order.description %></td>
        <td><%= order.address %></td>
        <td><%= order.price %></td>
        <td><%= order.customer_id %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', profile_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @order.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @order.description %>
</p>

<p>
  <strong>Address:</strong>
  <%= @order.address %>
</p>

<p>
  <strong>Price:</strong>
  <%= @order.price %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @order.customer_id %>
</p>

<p>
  <strong>Worker:</strong>
  <%= @order.worker_id %>
</p>
<p>
  <% @order.images.each do |img| %>
    <%= image_tag img.variant(resize: "500x500") %>
  <% end %>
</p>
<p>
  <% if current_customer %>
  <table>
    <thead>
      <tr>
        <th>Исполнитель</th>
        <th>Действие</th>
      </tr>
    </thead>
  <tbody>
    <% @workers.each do |worker| %>
      <tr>
        <td><%= link_to "#{worker.name}", worker_url(id: worker.id, order_id: @order.id) %></td>
      </tr>
    <% end %>
  </tbody>
  </table>

  <% elsif current_worker %>
    <%= form_tag response_to_orders_path(worker_id: current_worker.id, order_id: @order.id), method: :post do %>
    <%= submit_tag 'Откликнуться на заказ' %>
    <% end %>
      |
    <%end%>
    <%= link_to 'Back', :back %>
  </p>